version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:v1.8.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - qdrant

volumes:
  qdrant_data:
